#!/usr/bin/python3

print()
print("========================================================================")
print(" Welcome to the Grade Book Application, your comprehensive program for") 
print(" managing student records, course  registration, and GPA calculations.")
print("========================================================================")
print()
print("Select one of the options below based on what you need to accomplish now")
print()
print("0. Read the Grade Book Application's Introduction")
print("1. Create Student Record")
print("2. View Student Records")
print("3. Edit Student Records")
print("4. Create Course Record")
print("5. Register Student for a Course")
print("6. Register Student Grades")
print("7. Sort Students by their GPA Rankings")
print("8. Search Student by GPA obtained")
print("9. Generate Students' Transcripts")
print("10. Exit the Grade Book Application")
print()
print("Enter your choice [1-10]: ")
print()
